Navigation bar
dorksquad/frontend pull request #15
Opened 2021-07-25 05:00 UTC by JordanCaseCode

Adding nav bar and place holder pages for contact and  gallery

fixes : #9

2021-07-25 23:03 UTC, cgrountree requested changes
functionality looks good to me for a first pass. will obviously refine but a good place to start. just have some small formatting changes requested. i think we should work on a way to solve this automatically

2021-07-25 23:03 UTC, cgrountree commented on public/index.css
> +.pipeSide::after {
can this be kebab-case instead of camelCase to match the rest of the css file? or make the rest of the css file camelCase

2021-07-25 23:03 UTC, cgrountree commented on public/index.css
> +.pipeSide::before {
same as above

2021-07-25 23:03 UTC, cgrountree commented on src/App.js
> +import { HashRouter , Route, Switch, Redirect } from "react-router-dom";
fix the space before the comma? lol

2021-07-25 23:03 UTC, cgrountree commented on src/App.js
> +        </Route>
fix the formatting? lets figure out how to set up prettier configuration to auto fix this stuff for us

2021-07-25 23:03 UTC, cgrountree commented on src/components/Home.js
> +        <div >
remove space pls. really need to set up prettier config

2021-07-25 23:03 UTC, cgrountree commented on src/index.js
> +     <App />
pls remove

2021-07-26 01:34 UTC, cgrountree approved these changes
:exploding_head:

2021-07-26 23:41 UTC, cerountree approved these changes

2021-07-26 23:45 UTC, merged